version: '3.8'
services:
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dbtest
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"
volumes:
  db-data: